# Generated by Django 4.2 on 2023-05-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_profile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='socialLinkedIn',
            new_name='socialHashnode',
        ),
    ]
