# Generated by Django 4.2 on 2023-05-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_remove_profile_password'),
        ('project_api', '0003_alter_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_api.profile'),
        ),
    ]
